<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        let p1 = Promise.reject(123)
        // .catch(reason=>{console.log(reason,'p1_reason');})
        // 如果Promise.reject(123)传入的参数非promise对象，则返回结果为失败的promise对象
        // 如果是promise对象根据promise的参数的结果决定resolve的结果，如下不加catch或.then而不是.catch结果为失败
        // 
        let p2 = Promise.reject(new Promise((resolve,reject)=>{
            resolve('Error')
        })
        )
        // .catch((reason)=>{
        //     console.log(reason,'p2_reason');
        // })

        // 加了.catch都是成功回调，不加都为失败回调
        console.log(p1,'p1');//成功的promise回调
        console.log(p2,'p2');//成功的promise回调

    </script>
    
</body>
</html>